### ISSUE TITLE
No such file or directory: 'path/to/venv/lib/python3.8/site-packages/corpora/0.1.0'

### ISSUE THREAD

**Issue by emiljoha** [amperser/proselint#1084]
Using a new python3 virtual enviroment.
```
python3 -m virtualenv .
. bin/activate
```
Installing proselint with pip.
```
pip install proselint
```
Then running proselint -t causes this error.
```
proselint -t
Traceback (most recent call last):
  File "/home/emil/tmp/bin/proselint", line 8, in <module>
    sys.exit(proselint())
  File "/home/emil/tmp/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/emil/tmp/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/emil/tmp/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/emil/tmp/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/emil/tmp/lib/python3.8/site-packages/proselint/tools.py", line 45, in wrapped
    f(*args, **kwargs)
  File "/home/emil/tmp/lib/python3.8/site-packages/proselint/command_line.py", line 110, in proselint
    click.echo(timing_test())
  File "/home/emil/tmp/lib/python3.8/site-packages/proselint/command_line.py", line 37, in timing_test
    for file in os.listdir(corpus_path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/emil/tmp/lib/python3.8/site-packages/corpora/0.1.0'
```

OS: openSUSE Tumbleweed snapshot 20200625-0

**Comment by Nytelife26** [comment]
The corpus was removed for copyright reasons long ago. The timing option has been removed as of #1400, so this will be resolved in the next release.
