### ISSUE TITLE
Many errors when doing anything

### ISSUE THREAD

**Issue by Stakker** [amperser/proselint#1326]
Hey! Proselint was awesome as long as it worked (I used it via the Sublime Text plugin), but suddenly it stopped working... Now when I try anything, for example "proselint --demo", it dumps a bunch of errors. I installed (and reinstalled) version 0.13.0 from Homebrew on macOS 11.7.1.

This is what I get from "proselint --demo":

Traceback (most recent call last):
  File "/usr/local/bin/proselint", line 8, in <module>
    sys.exit(proselint())
             ^^^^^^^^^^^
  File "/usr/local/Cellar/proselint/0.13.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/proselint/0.13.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/proselint/0.13.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/proselint/0.13.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/proselint/0.13.0_1/libexec/lib/python3.11/site-packages/proselint/tools.py", line 34, in wrapped
    f(*args, **kwargs)
  File "/usr/local/Cellar/proselint/0.13.0_1/libexec/lib/python3.11/site-packages/proselint/command_line.py", line 112, in proselint
    config = load_options(config, default)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/proselint/0.13.0_1/libexec/lib/python3.11/site-packages/proselint/tools.py", line 187, in load_options
    user_options = json.load(open(path))
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Stakker** [comment]
Something about the config file did it. Creating the file again helped. *shrug*
