### ISSUE TITLE
proselint --initialize throws errors

### ISSUE THREAD

**Issue by skylerberg** [amperser/proselint#304]
```
skyler@sib5:~/.proselint|→  proselint --initialize
Traceback (most recent call last):
  File "/usr/local/bin/proselint", line 11, in <module>
    sys.exit(proselint())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/proselint/command_line.py", line 150, in proselint
    run_initialization()
  File "/usr/local/lib/python2.7/dist-packages/proselint/command_line.py", line 42, in run_initialization
    module = loader.find_module(module_name).load_module(module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/local/lib/python2.7/dist-packages/proselint/checks/butterick/symbols.py", line 16, in <module>
    from tools import memoize, existence_check
ImportError: No module named tools
```

**Comment by mkcode** [comment]
This happens for me as well.

Using:
                                                                                                                                                                        Python 2.7.10
pip 8.1.0 from /Library/Python/2.7/site-packages (python 2.7)
no virtualenv
just installed pip via `pip install proselint`
