### ISSUE TITLE
Could not open cache file

### ISSUE THREAD

**Issue by FabLabEP** [amperser/proselint#399]
Tried running proselint on:

Python 2.7.11 (default, Mar 14 2016, 12:08:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin

Get the following errors:

Could not open cache file .proselint/checks.garner.archaism.check, maybe name collision
on repeat for all checks

Then:

Traceback (most recent call last):
  File "/usr/local/bin/proselint", line 11, in <module>
    sys.exit(proselint())
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/proselint/command_line.py", line 192, in proselint
    errors = lint(f, debug=debug)
  File "/usr/local/lib/python2.7/site-packages/proselint/command_line.py", line 77, in lint
    result = check(text)
  File "/usr/local/lib/python2.7/site-packages/proselint/tools.py", line 59, in wrapped
    '%s; it probably has unhashable args'] % (call_to))
TypeError: unsupported operand type(s) for %: 'list' and 'unicode'

Any ideas what's going wrong?

**Comment by suchow** [comment]
This may be the same issue as #313.

**Comment by Decagon** [comment]
Closing because issue is fixed in #313
