### ISSUE TITLE
proselint choked on bad character

### ISSUE THREAD

**Issue by denispelli** [amperser/proselint#504]
my first attempt to use proselint choked on a bad character. (error message from macOS Terminal below). I have little experience with Python and Terminal, but it seems to be running. The plain text file was converted from Word by converting first to .odoc (because Word crashes when I ask for plain text), and then using macOS TextEdit to convert odoc to plain text. It seems unlikely that TextEdit would produce a bad text file. i attached the text file. 

Good news. I remembered that BBEdit has a zap gremlins command. After that, proselint worked. You might want to pass on that tip to others using proselint with BBEdit.

Thanks
Denis

p.s. The release notes for BBEdit mentions it's new command tool bbresults and gives a shout out to your proselint tool. This may encourage more users, like me, who are not familiar with Terminal. It would be nice if your READ ME offered a usage example, using bbresults, and explained that BBEdit has a menu command that results the path to the open file.

Denis Pelli
denis.pelli@nyu.edu

[Legibility87.txt](https://github.com/amperser/proselint/files/350720/Legibility87.txt)

Deniss-MBP-5K:~ denispelli$ proselint ~/Dropbox/legibility/Legibility87.txt | bbresults
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/proselint/command_line.py", line 116, in proselint
    errors = lint(f, debug=debug)
  File "/Library/Python/2.7/site-packages/proselint/tools.py", line 216, in lint
    text = input_file.read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 302, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 1322: invalid continuation byte
Deniss-MBP-5K:~ denispelli$

**Comment by denispelli** [comment]
p.s. 
proselint worked. It identified real problems in my ms (especially overuse of "very"), with little chaff, and I fixed them. Thanks!

**Comment by Decagon** [comment]
It looks like this issue was fixed on 0.6.1 (I get no errors running it); should this be closed?

**Comment by denispelli** [comment]
yes. thanks.
denis


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University
+1-646-258-7524 | denis.pelli@nyu.edu | http://psych.nyu.edu/pelli/ | Skype:
denispelli <#> | http://denispelli.com
<http://www.facebook.com/denispelli>

**Comment by jamesking** [comment]
Hello - I think I am getting a similar issue with version 0.7.0 of proselint. I have a folder of 38 markdown documents and this issue only occurs with one of them. 

I am not sure which character is throwing the error. According to the error message, it is `byte 0xc3 in position 1`. The first character in the document is a `-`. However, all the other markdown documents I have tested also start with a `-` and have no problems. 

I am using proselint via the linter-proselint Atom package. 

Trace: 

```
Error: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/proselint/command_line.py", line 116, in proselint
    errors = lint(f, debug=debug)
  File "/Library/Python/2.7/site-packages/proselint/tools.py", line 225, in lint
    result = check(text)
  File "/Library/Python/2.7/site-packages/proselint/tools.py", line 114, in wrapped
    value = f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/proselint/checks/misc/preferred_forms.py", line 177, in check
    return preferred_forms_check(text, preferences, err, msg)
  File "/Library/Python/2.7/site-packages/proselint/tools.py", line 296, in preferred_forms_check
    msg.format(p[0], txt),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
    at ChildProcess.<anonymous> (/Users/jamesking/.atom/packages/linter-proselint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
