### ISSUE TITLE
`proselint --demo` is broken on 0.6.0

### ISSUE THREAD

**Issue by viccuad** [amperser/proselint#513]
Hi,
Just tried version 0.6.0, and seems that the `replacements` adding is incorrectly handled
on 0.6.0:

``` console
$ proselint --demo
Traceback (most recent call last):
  File "/home/vic/.local/lib/python3.5/site-packages/proselint/command_line.py", line 116, in proselint
    errors = lint(f, debug=debug)
  File "/home/vic/.local/lib/python3.5/site-packages/proselint/tools.py", line 228, in lint
    (start, end, check, message, replacements) = error
ValueError: not enough values to unpack (expected 5, got 4)
```

**Comment by suchow** [comment]
I'm having trouble reproducing this problem:

```
❯ python --version
Python 3.5.0

❯ proselint --version
0.6.0

❯ proselint --demo --compact
-:11:5: dates_times.dates Apostrophes aren't needed for decades.
-:12:5: dates_times.dates Apostrophes aren't needed for decades.
-:13:17: dates_times.dates When specifying a date range, write 'from X to Y'.
-:13:36: dates_times.dates When specifying a date range, write 'from X to Y'.
-:14:1: dates_times.dates When specifying a month and year, no comma is needed.
-:15:4: dates_times.dates When specifying a month and year, 'of' is unnecessary.
-:16:6: dates_times.am_pm.lowercase_periods With lowercase letters, the periods are standard.
-:17:6: dates_times.am_pm.midnight_noon 12 a.m. and 12 p.m. are wrong and confusing. Use 'midnight' or 'noon'.
-:18:6: dates_times.am_pm.midnight_noon 'a.m.' is always morning; 'p.m.' is always night.
-:18:9: redundancy.nordquist Redundancy. Use 'p.m.' instead of 'p.m. at night.'.
-:21:19: leonard.exclamation.30ppm More than 30 ppm of exclamations. Keep them under control.
-:22:19: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).
-:23:19: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).
-:28:15: consistency.spelling Inconsistent spelling of 'centre' (vs. 'center').
-:29:34: consistency.spelling Inconsistent spelling of 'organize' (vs. 'organise').
-:30:1: consistency.spelling Inconsistent spelling of 'recognise' (vs. 'recognize').
-:33:1: misc.currency Incorrect use of symbols in $1000 USD.
-:34:33: typography.symbols.multiplication_symbol Use the multiplication symbol ×, not the letter x.
-:37:1: oxford.venery_terms The venery term is 'a herd of antelopes'.
-:38:1: oxford.venery_terms The venery term is 'a mob of emus'.
-:39:13: oxford.venery_terms The venery term is 'a bed of oysters'.
-:42:38: misc.mondegreens 'laid him on the green' is the preferred form.
-:43:1: misc.mondegreens 'a girl with kaleidoscope eyes' is the preferred form.
-:46:17: skunked_terms.misc 'deceptively' is a bit of a skunked term — impossible to use without issue. Find some other way to say it.
-:47:19: skunked_terms.misc 'decimate' is a bit of a skunked term — impossible to use without issue. Find some other way to say it.
-:48:1: skunked_terms.misc 'Hopefully,' is a bit of a skunked term — impossible to use without issue. Find some other way to say it.
-:56:14: leonard.exclamation.multiple Stop yelling. Keep your exclamation points under control. Found 3 times elsewhere.
-:58:4: hyperbolic.misc 'excited!!' is hyperbolic.
-:59:4: hyperbolic.misc 'excited!!!' is hyperbolic.
-:60:4: hyperbolic.misc 'excited!!!!' is hyperbolic.
-:67:1: spelling.able_atable -able vs. -atable. 'abbreviable' is the preferred spelling.
-:68:1: spelling.misc Misspelling. 'academically' is the preferred spelling.
-:69:1: garner.preferred_forms 'transshipped' is the preferred form.
-:70:14: spelling.er_or -er vs. -or. 'abettor' is the preferred spelling.
-:71:6: spelling.able_ible -able vs. -ible. 'adducible' is the preferred spelling.
-:72:19: spelling.er_or -er vs. -or. 'acquirer' is the preferred spelling.
-:73:15: garner.preferred_forms 'tortfeasor' is the preferred form.
-:74:10: garner.preferred_forms 'off' is the preferred form.
-:74:29: needless_variants.misc Needless variant. 'catch fire' is the preferred form.
-:75:7: misc.many_a 'many a' requires a singular verb.
-:76:1: garner.preferred_forms 'in the meantime' is the preferred form.
-:77:1: misc.suddenly Suddenly is nondescript, slows the action, and warns your reader.
-:80:12: mixed_metaphors.misc.misc Mixed metaphor. Try 'fasten your seatbelts'.
-:81:5: mixed_metaphors.misc.misc Mixed metaphor. Try 'cream rises to the top'.
-:82:5: mixed_metaphors.misc.bottleneck Mixed metaphor — bottles with big necks are easy to pass through.
-:82:32: typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
-:85:7: weasel_words.very Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be. Found 4 times elsewhere.
-:86:1: redundancy.garner Redundancy. Use 'approximately' instead of 'approximately about'.
-:87:1: garner.redundancy.ras RAS syndrome. Use 'ATM' instead of 'atm machine'.
-:88:4: redundancy.garner Redundancy. Use 'associate' instead of 'associate together'.
-:89:6: redundancy.garner Redundancy. Use 'obvious' instead of 'blatantly obvious'.
-:90:3: uncomparables.misc Comparison of an uncomparable: 'very unique ' is not comparable.
-:92:5: redundancy.garner Redundancy. Use 'circumstances' instead of 'surrounding circumstances'.
-:93:14: misc.illogic 'much-needed gap' is illogical.
-:94:1: cliches.write_good 'To coin a phrase' is a cliché.
-:94:2: misc.illogic.coin You can't coin an existing phrase. Did you mean 'borrow'?
-:97:1: misc.suddenly Suddenly is nondescript, slows the action, and warns your reader.
-:98:1: leonard.hell Never use the words 'all hell broke loose'.
-:101:1: cliches.write_good 'under the weather' is a cliché.
-:102:6: cliches.write_good 'a chip off the old block' is a cliché.
-:103:3: cliches.garner 'quantum leap' is cliché.
-:104:5: cliches.garner 'cutting edge' is cliché.
-:104:62: cliches.garner 'crystal clear.' is cliché.
-:104:62: cliches.write_good 'crystal clear.' is a cliché.
-:105:8: cliches.garner 'thought leader.' is cliché.
-:109:1: security.credit_card Don't put credit card numbers in plain text.
-:110:1: security.password Don't put passwords in plain text.
-:112:1: security.password Don't put passwords in plain text.
-:115:1: misc.commercialese 'inst.' is commercialese.
-:119:1: archaism.misc 'boughten' is archaic.
-:125:1: misc.chatspeak 'brb' is chatspeak. Write it out.
-:129:15: ogilvy.pretension Jargon words like this one are the hallmarks of a pretentious ass.
-:132:1: airlinese.misc 'enplanement' is airlinese.
-:133:10: airlinese.misc 'taking off momentarily.' is airlinese.
-:136:6: misc.tense_present 'up to 50% or More!'.
-:137:1: misc.tense_present 'between you and i'.
-:138:10: misc.tense_present 'on accident'.
-:139:1: misc.tense_present 'I feel nauseous'.
-:142:14: garner.phrasal_adjectives.ly No hyphen is necessary in phrasal adjectives with an adverb ending in -ly.
-:143:5: garner.phrasal_adjectives.examples Hyphenate 'English speaking people', a phrasal adjective, as 'English-speaking people'.
-:144:3: garner.phrasal_adjectives.examples Hyphenate 'big ticket item.', a phrasal adjective, as 'big-ticket item'.
-:145:3: garner.phrasal_adjectives.examples Hyphenate 'right wing militia.', a phrasal adjective, as 'right-wing militia'.
-:148:1: spelling.misc Misspelling. 'highfalutin' is the preferred spelling.
-:149:19: spelling.able_ible -able vs. -ible. 'inadmissible' is the preferred spelling.
-:150:8: garner.preferred_forms 'Khrushchev' is the preferred form.
-:151:8: spelling.misc Misspelling. 'inundated' is the preferred spelling.
-:152:1: needless_variants.misc Needless variant. 'knickknack' is the preferred form.
-:153:8: garner.preferred_forms 'shoo-in' is the preferred form.
-:154:1: spelling.athletes Misspelling of athlete's name. 'Brett Favre' is the preferred form.
-:154:17: spelling.athletes Misspelling of athlete's name. 'Dwyane Wade' is the preferred form.
-:155:5: spelling.misc Misspelling. 'chronicles' is the preferred spelling.
-:159:3: strunk_white.composition Try 'ignored' instead of 'did not pay attention to'.
-:160:3: strunk_white.composition Try 'ignored' instead of 'did not pay any attention to'.
-:163:2: typography.symbols.copyright (c) is a goofy alphabetic approximation, use the symbol ©.
-:164:2: typography.symbols.trademark (R) is a goofy alphabetic approximation, use the symbol ®.
-:165:29: typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
-:168:5: terms.denizen_labels.norris Would you like 'Mancunian'?
-:169:28: terms.denizen_labels.garner 'Michigander' is the preferred denizen label.
-:170:28: terms.denizen_labels.garner 'Coloradan' is the preferred denizen label.
-:173:5: sexism.misc Gender bias. Use 'lawyer' instead of 'lady lawyer'.
-:174:37: sexism.misc Gender bias. Use 'husband and wife' instead of 'man and wife.'.
-:175:22: sexism.misc Gender bias. Use 'chair' instead of 'chairman'.
-:178:8: garner.punctuation Misplaced punctuation. It's 'et al.'
-:181:34: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "".
-:182:22: uncomparables.misc Comparison of an uncomparable: 'very unique.' is not comparable.
-:186:1: pinker.metadiscourse Excessive metadiscourse.
-:189:1: pinker.scare_quotes Misuse of 'scare quotes'. Delete them.
-:190:1: pinker.apologizing Excessive apologizing.
-:191:1: pinker.metadiscourse Excessive metadiscourse.
-:191:39: hedging.misc Hedging. Just say it.
-:192:1: pinker.narcisissm Professional narcisissm. Talk about the subject, not its study.
-:193:1: pinker.latin Use English. 'having made the necessary changes' is the preferred form.
```

**Comment by viccuad** [comment]
I can reproduce it on Debian Testing, python 3.5.2, with proselint 0.6.1, but not with 0.5.3:

```console
vic@clotho ~$ python3 --version
Python 3.5.2
vic@clotho ~$ whereis proselint
proselint:
vic@clotho ~$ pip3 install --user proselint
Collecting proselint
  Using cached proselint-0.6.1-py3-none-any.whl
Collecting six (from proselint)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting future (from proselint)
Collecting click (from proselint)
Installing collected packages: six, future, click, proselint
Successfully installed click-6.3 future-0.15.2 proselint-0.6.1 six-1.10.0
vic@clotho ~$ proselint --demo
  File "/home/vic/.local/lib/python3.5/site-packages/proselint/command_line.py", line 116, in proselint
    errors = lint(f, debug=debug)
  File "/home/vic/.local/lib/python3.5/site-packages/proselint/tools.py", line 228, in lint
    (start, end, check, message, replacements) = error
ValueError: not enough values to unpack (expected 5, got 4)
```

**Comment by viccuad** [comment]
I found the culprit: databases from old versions in `~/.proselint/*`. Funnily enough, I tried reproducing it again in by installing 0.5.3 to 0.7.0 and running `proselint --demo` on a chroot, and I couldn't.
