### ISSUE TITLE
Running a local version of Proselint

### ISSUE THREAD

**Issue by roshancvp** [amperser/proselint#535]
I tried running `python app.py` and expected `* Running on http://127.0.0.1:5000/` but ran into some errors:

```
/Users/Roshan/anaconda/lib/python3.5/site-packages/flask_limiter/extension.py:124: UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration
  UserWarning
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/Users/Roshan/anaconda/lib/python3.5/site-packages/flask_limiter/extension.py:124: UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration
  UserWarning
 * Debugger is active!
 * Debugger pin code: 172-786-099
```

(When I visit the website on localhost:5000 it returns 404 status codes)

**Comment by suchow** [comment]
I'd recommend using Foreman (https://theforeman.org/) and running `foreman start`.

**Comment by roshancvp** [comment]
Thanks! I'll try that.

**Comment by Decagon** [comment]
I'm having a similar problem. After installing rq, apscheduler, gmail, redis, and foreman I get the following error:
```

16:34:24 web.1    | unknown command: gunicorn app:app --log-file=-
16:34:24 worker.1 | started with pid 6645
16:34:24 clock.1  | started with pid 6646
16:34:24 worker.1 | Traceback (most recent call last):
16:34:24 worker.1 |   File "worker.py", line 18, in <module>
16:34:24 worker.1 |     worker.work()
16:34:24 worker.1 |   File "/home/decagon/.local/lib/python2.7/site-packages/rq/worker.py", line 423, in work
16:34:24 worker.1 |     self.register_birth()
16:34:24 worker.1 |   File "/home/decagon/.local/lib/python2.7/site-packages/rq/worker.py", line 242, in register_birth
16:34:24 worker.1 |     if self.connection.exists(self.key) and \
16:34:24 worker.1 |   File "/home/decagon/.local/lib/python2.7/site-packages/redis/client.py", line 855, in exists
16:34:24 worker.1 |     return self.execute_command('EXISTS', name)
16:34:24 worker.1 |   File "/home/decagon/.local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
16:34:24 worker.1 |     connection.send_command(*args)
16:34:24 worker.1 |   File "/home/decagon/.local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
16:34:24 worker.1 |     self.send_packed_command(self.pack_command(*args))
16:34:24 worker.1 |   File "/home/decagon/.local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
16:34:24 worker.1 |     self.connect()
16:34:24 worker.1 |   File "/home/decagon/.local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
16:34:24 worker.1 |     raise ConnectionError(self._error_message(e))
16:34:24 worker.1 | redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
16:34:25 clock.1  | Traceback (most recent call last):
16:34:25 clock.1  |   File "clock.py", line 23, in <module>
16:34:25 clock.1  |     password = os.environ['gmail_password']
16:34:25 clock.1  |   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
16:34:25 clock.1  |     raise KeyError(key)
16:34:25 clock.1  | KeyError: 'gmail_password'
16:34:25 worker.1 | exited with code 1
16:34:25 system   | sending SIGTERM to all processes
/var/lib/gems/2.3.0/gems/foreman-0.82.0/lib/foreman/engine.rb:193:in `kill': no implicit conversion from nil to integer (TypeError)
        from /var/lib/gems/2.3.0/gems/foreman-0.82.0/lib/foreman/engine.rb:193:in `kill_children'
        from /var/lib/gems/2.3.0/gems/foreman-0.82.0/lib/foreman/engine.rb:465:in `terminate_gracefully'
        from /var/lib/gems/2.3.0/gems/foreman-0.82.0/lib/foreman/engine.rb:431:in `wait_for_shutdown_or_child_termination'
        from /var/lib/gems/2.3.0/gems/foreman-0.82.0/lib/foreman/engine.rb:60:in `start'
        from /var/lib/gems/2.3.0/gems/foreman-0.82.0/lib/foreman/cli.rb:41:in `start'
        from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/2.3.0/gems/foreman-0.82.0/bin/foreman:7:in `<top (required)>'
        from /usr/local/bin/foreman:23:in `load'
        from /usr/local/bin/foreman:23:in `<main>'
```

It looks like it's trying to connect to gmail (which it doesn't have access to because the password is in an environment variable that's not set) and redis (which isn't running.) Is there a way to programatically disable gmail and redis?

**Comment by michaelpacer** [comment]
@suchow Can you remember why it does call into gmail? Is it just to be able to manage the email forwarding? If so, should we alter it to be a site where it only enables that feature if the authorisation details are available?
