### ISSUE TITLE
Missing module anydbm when pip installing

### ISSUE THREAD

**Issue by ghost** [amperser/proselint#796]
```
ash@mini:~> sudo pip3 install proselint
Collecting proselint
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/1b/d2/2e6afa3f933a12bfb1eb588f1ec8c26f915935356d8a0e51b2e5c53bfd04/proselint-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-m2mb9_r1/proselint/proselint/tools.py", line 20, in <module>
        import dbm
      File "/usr/lib64/python3.4/_import_failed/dbm.py", line 17, in <module>
        to install it.""".format(__name__, package))
    ImportError: Module 'dbm' is not installed.
    Use:
      sudo zypper install python3-dbm
    to install it.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-m2mb9_r1/proselint/setup.py", line 4, in <module>
        from proselint.version import __version__
      File "/tmp/pip-install-m2mb9_r1/proselint/proselint/__init__.py", line 2, in <module>
        from . import tools
      File "/tmp/pip-install-m2mb9_r1/proselint/proselint/tools.py", line 22, in <module>
        import anydbm as dbm
    ImportError: No module named 'anydbm'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-m2mb9_r1/proselint/
```

**Comment by ArneBachmann** [comment]
OK; the solution was written out:
`sudo zypper install python3-dbm`
but still... can't that be made a pip dependency?

**Comment by joshmgrant** [comment]
Definitely a good catch! What OS and Python version are you using?

**Comment by ArneBachmann** [comment]
On opensuse
Zypper is the package manager

**Comment by joshmgrant** [comment]
So based on some research, it looks like on some versions of openSUSE `python3-dbm` is missing even though it's a stock module that should with standard Python installations. Based on this you have a few options:

1. Follow the provided advice and run `sudo zypper install python3-dbm` which will resolve this dependency issue
2. Update your openSUSE to a newer version (if possible)
3. Open a PR to add `python3-dbm` to the requirements.txt file directly. I can do this for you but it may not solve the issue on openSUSE.

Let me know what you think!

**Comment by ArneBachmann** [comment]
1. Yeah, the error message was already helpful and told me to `sudo zypper install python3-dbm` which worked fine. The fact that there is a message with a solution, however, makes me think why not have the solution in place, but this may really be a system maintainers choice (OpenSuse Python package maintainer decided to not includ ethe package?).
2. I'm on 42.3 which is pretty new, just last week OpenSUSE 15 was released, which I won't install in the near future, but one could look into that.
3. Could work, but could also be a very specific bugfix not working on all OSs. I think it' spossible to define optional requirements, or extra requirements in the setup.py or requirements.txt, which use special environment checks to conditionally add the requirement.

**Comment by joshmgrant** [comment]
I think I like the idea of a conditional import based on the OS. I'm going to open a PR as the first crack at this.

**Comment by joshmgrant** [comment]
So based on some research, it looks like on some versions of openSUSE `python3-dbm` is missing even though it's a stock module that should with standard Python installations. Based on this you have a few options:

1. Follow the provided advice and run `sudo zypper install python3-dbm` which will resolve this dependency issue
2. Update your openSUSE to a newer version (if possible)
3. Open a PR to add `python3-dbm` to the requirements.txt file directly. I can do this for you but it may not solve the issue on openSUSE.

#797 

Let me know what you think!

**Comment by joshmgrant** [comment]
#797

**Comment by joshmgrant** [comment]
Huh, this is more complicated than I thought (see above PR @ArneBachmann)

**Comment by joshmgrant** [comment]
Huh, this is more complicated than I thought (see above PR @ArneBachmann)
